apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
commonLabels:
  env: production
resources:
- ../../base
patches:
- path: env.yaml
  target:
    kind: Deployment
images:
- digest: sha256:60165038a5dc4f4577dcebf6c922ca59b2b4d29ba307597cd5a8b60896b9dc27
  name: account
  newName: ghcr.io/hu-tao-supremacy/account-prod
- digest: sha256:8e65c0c276513059a8eb9d43468ee5c9f251e7b80bbbdbf7feb76e3c70087b0a
  name: api-gateway
  newName: ghcr.io/hu-tao-supremacy/api-gateway-prod
- digest: sha256:2a2b5f81e7c9d906edfb1a7bf5ea0b7da26a4e6d19b4c66400c6d892bdd85b3e
  name: organizer
  newName: ghcr.io/hu-tao-supremacy/organizer-prod
- digest: sha256:f35b73ed2ce8ec5baefcb1a99a633ac4ee4f91e4c63361fcf35da682a9e8735e
  name: participant
  newName: ghcr.io/hu-tao-supremacy/participant-prod
