apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
commonLabels:
  env: production
resources:
- ../../base
patches:
- path: env.yaml
  target:
    kind: Deployment
images:
- digest: sha256:9e811253a0f2fa2a1e01a90756756f63e563db052fb0cae8a33987e2f17ceb17
  name: account
  newName: ghcr.io/hu-tao-supremacy/account-prod
- digest: sha256:dfeea649e769a741c48ed5dbb3292677491a563ae2eca3a2dffbca9989873375
  name: api-gateway
  newName: ghcr.io/hu-tao-supremacy/api-gateway-prod
- digest: sha256:ef1df12761d58d5f3ab4765547c2f161ca1f9d64a8a55b09a772339439150145
  name: organizer
  newName: ghcr.io/hu-tao-supremacy/organizer-prod
- digest: sha256:a02693d42e85d6dc3eaa1bc33616ea8129a25f0e36ea408b07c917ae39a5ff77
  name: participant
  newName: ghcr.io/hu-tao-supremacy/participant-prod
