apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
commonLabels:
  env: production
resources:
- ../../base
patches:
- path: env.yaml
  target:
    kind: Deployment
images:
- digest: sha256:1b931fdb2afda5fcf8e31907e4f9afe35f7ce820b740fe35f755d1289e0bfe26
  name: account
  newName: ghcr.io/hu-tao-supremacy/account-prod
- digest: sha256:3bceff77df752eb89119d417adb1aa4f73e5348ea4c611b8a2b968a71bb4081d
  name: api-gateway
  newName: ghcr.io/hu-tao-supremacy/api-gateway-prod
- digest: sha256:91a515abb7eabb9e540b1ea04d2bc54ddfcc92ea415e9bd1b200b58ce7ebd169
  name: organizer
  newName: ghcr.io/hu-tao-supremacy/organizer-prod
- digest: sha256:901d19660fb37242c9e2a54d7ccc0f517d1b71e6f92f6f8eceda6a2ae2ba1d2d
  name: participant
  newName: ghcr.io/hu-tao-supremacy/participant-prod
