apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
resources:
- ../../base
images:
- digest: sha256:776a81bb50ed0453abcaf45036a8a08f9d6f233d2683024ae5ccf26531805b16
  name: account
  newName: ghcr.io/hu-tao-supremacy/account-prod
