apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
commonLabels:
  env: production
resources:
- ../../base
patches:
- path: env.yaml
  target:
    kind: Deployment
images:
- digest: sha256:3c638ad1218e9395ac452ff66232b294e2d4ae1f3bfa998c09ca0e2da241af94
  name: account
  newName: ghcr.io/hu-tao-supremacy/account-prod
- digest: sha256:8e65c0c276513059a8eb9d43468ee5c9f251e7b80bbbdbf7feb76e3c70087b0a
  name: api-gateway
  newName: ghcr.io/hu-tao-supremacy/api-gateway-prod
- digest: sha256:e854a324a69717f782f85f1200ccf987a7604dcd31e5661b598a24fd35cc2bf3
  name: organizer
  newName: ghcr.io/hu-tao-supremacy/organizer-prod
- digest: sha256:da7afedab7a49c65294ba6f759bc0a706f1ddc1250007eefe3916ae5899ca41c
  name: participant
  newName: ghcr.io/hu-tao-supremacy/participant-prod
