apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
commonLabels:
  env: production
resources:
- ../../base
patches:
- path: env.yaml
  target:
    kind: Deployment
images:
- digest: sha256:f1d31dc2319db82f2a7d6de48cd3f8aa8ba0c226f756cc1791ba467264943343
  name: account
  newName: ghcr.io/hu-tao-supremacy/account-prod
- digest: sha256:fe45cacff9e4544525737c2955b0e165fd6e31bb899ac3e0987c1fb64e1093b4
  name: api-gateway
  newName: ghcr.io/hu-tao-supremacy/api-gateway-prod
- digest: sha256:91a515abb7eabb9e540b1ea04d2bc54ddfcc92ea415e9bd1b200b58ce7ebd169
  name: organizer
  newName: ghcr.io/hu-tao-supremacy/organizer-prod
- digest: sha256:aefd022b3208b3bccfa3c447e17d37dc8740ffe4727cdc192a750a4623bbbf02
  name: participant
  newName: ghcr.io/hu-tao-supremacy/participant-prod
