apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
commonLabels:
  env: production
resources:
- ../../base
patches:
- path: env.yaml
  target:
    kind: Deployment
images:
- digest: sha256:7167dcaabd7e79795c9561c922fa6cdad19dce446d6dbc23d731a48a4587e7ec
  name: account
  newName: ghcr.io/hu-tao-supremacy/account-prod
- digest: sha256:87ddf4fa3ace6a90d6d527e3bc03a09bbc00c3757df8269f34d57a3114f3ee85
  name: api-gateway
  newName: ghcr.io/hu-tao-supremacy/api-gateway-prod
- digest: sha256:8fcecadab58bd6eb6ab59fc170fc022cf9eb080fb43d25a0e7cde7b10f0efbb3
  name: organizer
  newName: ghcr.io/hu-tao-supremacy/organizer-prod
- digest: sha256:2d39b4bde14ef11e56110e3e4f8ab33c23292855ae845fd664a9d09cde60f797
  name: participant
  newName: ghcr.io/hu-tao-supremacy/participant-prod
