apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
commonLabels:
  env: production
resources:
- ../../base
patches:
- path: env.yaml
  target:
    kind: Deployment
images:
- digest: sha256:cdf20378d0045ca257a3f769a93ca6d4f0c63ca57951f41da638d0be8fe702a4
  name: account
  newName: ghcr.io/hu-tao-supremacy/account-prod
- digest: sha256:1be833d0d5116261b0ea622b57a3c170e19bae7b2bae08a6a192ab103a85902a
  name: api-gateway
  newName: ghcr.io/hu-tao-supremacy/api-gateway-prod
- digest: sha256:303dc2a921bbfa8054d1f03a5555226028273bb79ad9983a6cb28b0dc642aaad
  name: organizer
  newName: ghcr.io/hu-tao-supremacy/organizer-prod
- digest: sha256:8102c1e8140c919956ece1d503d0ac271e83d3fe2643cbd0fb204636669c2bff
  name: participant
  newName: ghcr.io/hu-tao-supremacy/participant-prod
- digest: sha256:96654b0fe31fb4a1983aa26d549b5a4ddea2a5267851eeecd0f740c83caed15b
  name: personalization
  newName: ghcr.io/hu-tao-supremacy/personalization-prod
