apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
resources:
- ../../base
images:
- digest: sha256:e7e11e514f8c0124b020c2dca63b19e0647f2a1a73ddd090b6351ac345fd6b9e
  name: account
  newName: ghcr.io/hu-tao-supremacy/deploys/account-prod
