apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
commonLabels:
  env: production
resources:
- ../../base
patches:
- path: env.yaml
  target:
    kind: Deployment
images:
- digest: sha256:dd40ead4fa3ee3e28abb6a3f86c965b471db452f2472f2584f102bac24674798
  name: account
  newName: ghcr.io/hu-tao-supremacy/account-prod
- digest: sha256:cc00cb8fcf8f6187397e5f37a6fd7d2c20f0ad47e519eed083bed8679c38f1b0
  name: api-gateway
  newName: ghcr.io/hu-tao-supremacy/api-gateway-prod
- digest: sha256:303dc2a921bbfa8054d1f03a5555226028273bb79ad9983a6cb28b0dc642aaad
  name: organizer
  newName: ghcr.io/hu-tao-supremacy/organizer-prod
- digest: sha256:b2e2dbe3249fe3c406657852216e4c833a8bd2559dc51c9bf67584e0b4d504cd
  name: participant
  newName: ghcr.io/hu-tao-supremacy/participant-prod
- digest: sha256:ae380832c741099405e15b54a46fa1c9853dc7c765902b6aa07231a4de98050d
  name: personalization
  newName: ghcr.io/hu-tao-supremacy/personalization-prod
