apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
commonLabels:
  env: production
resources:
- ../../base
patches:
- path: env.yaml
  target:
    kind: Deployment
images:
- digest: sha256:1a1142cf09f68c229a630cf25a3b9dfcf5858fa7d2f5816dd6aed7f70a7e5bfe
  name: account
  newName: ghcr.io/hu-tao-supremacy/account-prod
- digest: sha256:0b6ab00a88a2bb7ac284556bb1a440fac0a7098fef41a75bdc81ae71cde552b4
  name: api-gateway
  newName: ghcr.io/hu-tao-supremacy/api-gateway-prod
- digest: sha256:91a515abb7eabb9e540b1ea04d2bc54ddfcc92ea415e9bd1b200b58ce7ebd169
  name: organizer
  newName: ghcr.io/hu-tao-supremacy/organizer-prod
- digest: sha256:ad74fd19f02e5f12cea92247114a6a333adfdd82005e5f81513357ca6b5a0826
  name: participant
  newName: ghcr.io/hu-tao-supremacy/participant-prod
