apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
commonLabels:
  env: production
resources:
- ../../base
patches:
- path: env.yaml
  target:
    kind: Deployment
images:
- digest: sha256:3bba9b058e852533f971aea574549789a455b86b54d361dfc358559860f9fb05
  name: account
  newName: ghcr.io/hu-tao-supremacy/account-prod
- digest: sha256:8acb66c00f9ad7a2541a6acddd36f9edfe1bf764ffe8e2773d18e6b3cd2f7ffa
  name: api-gateway
  newName: ghcr.io/hu-tao-supremacy/api-gateway-prod
- digest: sha256:927e9cbfb08718d17363d848de98b7921b5144e0d87697cc4b42bad3cfc4020a
  name: organizer
  newName: ghcr.io/hu-tao-supremacy/organizer-prod
- digest: sha256:f61b57c7f1a534d0fa1d8e13b7bd6f2660198b02082e748a2fa2614e4fe61ff5
  name: participant
  newName: ghcr.io/hu-tao-supremacy/participant-prod
