apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
commonLabels:
  env: production
resources:
- ../../base
patches:
- path: env.yaml
  target:
    kind: Deployment
images:
- digest: sha256:bce0823b7ef920b32e9b90994165eaa5f194a83d611e8846c605850bd8756b7d
  name: account
  newName: ghcr.io/hu-tao-supremacy/account-prod
- digest: sha256:3403e865a92bcaa6166360e5cbad8f1727640a53c49a9581fa832ff6429575c9
  name: api-gateway
  newName: ghcr.io/hu-tao-supremacy/api-gateway-prod
- digest: sha256:91a515abb7eabb9e540b1ea04d2bc54ddfcc92ea415e9bd1b200b58ce7ebd169
  name: organizer
  newName: ghcr.io/hu-tao-supremacy/organizer-prod
- digest: sha256:3fccbb60f834b2552017e1eed3faf28f7282d122ca970bba40d2a5c9911ff178
  name: participant
  newName: ghcr.io/hu-tao-supremacy/participant-prod
