apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
commonLabels:
  env: production
resources:
- ../../base
patches:
- path: env.yaml
  target:
    kind: Deployment
images:
- digest: sha256:9009b9e708dbfe4b5ad11b1eb95aef42ec943032b9e2340e56371e69ba6c9395
  name: account
  newName: ghcr.io/hu-tao-supremacy/account-prod
- digest: sha256:03851dc7cea0bdd53d6f0f682fc21c427a8a255bc6385939f6af352f635d8f0c
  name: api-gateway
  newName: ghcr.io/hu-tao-supremacy/api-gateway-prod
- digest: sha256:f1c835136e6e403af4b1302df1f3ecafa4ab58b8fc630a1c305d107289e3b4ca
  name: participant
  newName: ghcr.io/hu-tao-supremacy/participant-prod
