apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
commonLabels:
  env: production
resources:
- ../../base
patches:
- path: env.yaml
  target:
    kind: Deployment
images:
- digest: sha256:dd40ead4fa3ee3e28abb6a3f86c965b471db452f2472f2584f102bac24674798
  name: account
  newName: ghcr.io/hu-tao-supremacy/account-prod
- digest: sha256:39471e1ad4bec1500b7754af51fe0bdda36af9889bfb5c4bf20c9f4b515aa483
  name: api-gateway
  newName: ghcr.io/hu-tao-supremacy/api-gateway-prod
- digest: sha256:303dc2a921bbfa8054d1f03a5555226028273bb79ad9983a6cb28b0dc642aaad
  name: organizer
  newName: ghcr.io/hu-tao-supremacy/organizer-prod
- digest: sha256:9b9bcf405b3eeed2871c13baa26cfabb9e37ff8a1758fc70fc2ae0cb2a979532
  name: participant
  newName: ghcr.io/hu-tao-supremacy/participant-prod
- digest: sha256:051d099c8d20405c3cf60e5c43edc4729aff42cf81638cddd9d7ff8bcbdf92c8
  name: personalization
  newName: ghcr.io/hu-tao-supremacy/personalization-prod
