apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
resources:
- ../../base
images:
- digest: sha256:21b3c2c0246013097837892d4b14211fd4620bfe4ceb0c1f1229635b266eaa1a
  name: account
  newName: ghcr.io/hu-tao-supremacy/account-prod
