apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
commonLabels:
  env: production
resources:
- ../../base
patches:
- path: env.yaml
  target:
    kind: Deployment
images:
- digest: sha256:ac4968ca8940acdb0f24263a2188bc55e7a95dbee00bdd849f159545b118acdf
  name: account
  newName: ghcr.io/hu-tao-supremacy/account-prod
- digest: sha256:03851dc7cea0bdd53d6f0f682fc21c427a8a255bc6385939f6af352f635d8f0c
  name: api-gateway
  newName: ghcr.io/hu-tao-supremacy/api-gateway-prod
- digest: sha256:dc8920f15189fd5b9e3741f6a06aa29be2aeed057f20acc06803ff991cd15fc7
  name: participant
  newName: ghcr.io/hu-tao-supremacy/participant-prod
