apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
commonLabels:
  env: production
resources:
- ../../base
patches:
- path: env.yaml
  target:
    kind: Deployment
images:
- digest: sha256:cdf20378d0045ca257a3f769a93ca6d4f0c63ca57951f41da638d0be8fe702a4
  name: account
  newName: ghcr.io/hu-tao-supremacy/account-prod
- digest: sha256:49f0b117a0d4b7ae25b902332628d84e1d3d466a2aebfa80abbdeba74d62c57a
  name: api-gateway
  newName: ghcr.io/hu-tao-supremacy/api-gateway-prod
- digest: sha256:303dc2a921bbfa8054d1f03a5555226028273bb79ad9983a6cb28b0dc642aaad
  name: organizer
  newName: ghcr.io/hu-tao-supremacy/organizer-prod
- digest: sha256:bc2d4692a80f5dafa82762ba080312682edd7dd3e597c9256bc1f82e56818266
  name: participant
  newName: ghcr.io/hu-tao-supremacy/participant-prod
- digest: sha256:96654b0fe31fb4a1983aa26d549b5a4ddea2a5267851eeecd0f740c83caed15b
  name: personalization
  newName: ghcr.io/hu-tao-supremacy/personalization-prod
