apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ingress-production
  namespace: istio-system
spec:
  secretName: ingress-production
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - whoami.onepass.app
    - argocd.onepass.app
    - grafana.onepass.app
    - api.onepass.app
    - graph.onepass.app
    - lighthouse.onepass.app
    - api-staging.onepass.app
