apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: istio-system
spec:
  template:
    spec:
      containers:
        - name: grafana
          env:
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "false"
          ports:
            - containerPort: 3000
              name: service
              protocol: TCP
            - containerPort: 3000
              name: grafana
              protocol: TCP
            - $patch: replace
