apiVersion: v1
kind: Service
metadata:
  labels:
    app: personalization
  name: personalization
spec:
  type: ClusterIP
  ports:
    - port: 50051
      protocol: TCP
      targetPort: 50051
      name: grpc
  selector:
    app: personalization
