apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-gateway-prod
  namespace: default
spec:
  hosts:
    - "api.onepass.app"
  gateways:
    - default-gateway
  http:
    - route:
        - destination:
            # <service>.<namespace>.svc.cluster.local
            host: api-gateway-prod.hts.svc.cluster.local
            port:
              number: 3000
