apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd
  namespace: default
spec:
  hosts:
    - "argocd.onepass.app"
  gateways:
    - default-gateway
  http:
    - route:
        - destination:
            # <service>.<namespace>.svc.cluster.local
            host: argocd-server.argocd.svc.cluster.local
            port:
              number: 80
