apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificates/issuers/staging.yaml
  - certificates/issuers/production.yaml
  - certificates/ingress-production.yaml
  - gateways/https-redirect.yaml
  - gateways/default-gateway.yaml
  - gateways/whoami.yaml
  - gateways/argocd.yaml
  - gateways/grafana.yaml
  - gateways/api-gateway-dev.yaml
  - gateways/api-gateway-prod.yaml
  - gateways/graph.yaml
  - gateways/lighthouse.yaml
  - https://raw.githubusercontent.com/istio/istio/release-1.9/samples/addons/prometheus.yaml
  - https://raw.githubusercontent.com/istio/istio/release-1.9/samples/addons/grafana.yaml
patchesStrategicMerge:
  - patches/grafana.config.yaml
  - patches/grafana.deployment.yaml
