apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: account
  name: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  strategy: {}
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - image: account
          name: account
          ports:
            - containerPort: 50051
              name: grpc
          resources: {}
          env:
            - name: GRPC_PORT
              value: "50051"
status: {}
