apiVersion: v1
kind: Service
metadata:
  labels:
    app: account
  name: account
spec:
  type: ClusterIP
  ports:
    - port: 50051
      protocol: TCP
      targetPort: 50051
      name: grpc
  selector:
    app: account
