apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: istio-system
data:
  grafana.ini: |
    [server]
    root_url = https://grafana.onepass.app
    [auth.anonymous]
    enabled = false
    [auth.github]
    enabled = true
    scopes = user:email,read:org
    auth_url = https://github.com/login/oauth/authorize
    token_url = https://github.com/login/oauth/access_token
    api_url = https://api.github.com/user
    allow_sign_up = true
    allowed_organizations = hu-tao-supremacy
    client_id = $GRAFANA_GITHUB_APP_CLIENT_ID
    client_secret = $GRAFANA_GITHUB_APP_CLIENT_SECRET
