apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hts
resources:
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml
  - account/deployment.yaml
  - account/service.yaml
  - facility/deployment.yaml
  - facility/service.yaml
  - participant/deployment.yaml
  - participant/service.yaml
  - organizer/deployment.yaml
  - organizer/service.yaml
vars:
  - name: HTS_NAMESPACE
    objref:
      kind: Service
      name: account
      apiVersion: v1
    fieldref:
      fieldpath: metadata.namespace
  - name: HTS_SVC_ACCOUNT
    objref:
      kind: Service
      name: account
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: HTS_SVC_FACILITY
    objref:
      kind: Service
      name: facility
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: HTS_SVC_ORGANIZER
    objref:
      kind: Service
      name: organizer
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: HTS_SVC_PARTICIPANT
    objref:
      kind: Service
      name: participant
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
patches:
  - path: env.yaml
    target:
      kind: Deployment
  - path: env-staging.yaml
    target:
      kind: Deployment
      labelSelector: "env=staging"
  - path: env-production.yaml
    target:
      kind: Deployment
      labelSelector: "env=production"
