apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hts
commonAnnotations:
  traffic.sidecar.istio.io/excludeOutboundPorts: "5432"
resources:
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml
  - account/deployment.yaml
  - account/service.yaml
  - facility/deployment.yaml
  - facility/service.yaml
  - participant/deployment.yaml
  - participant/service.yaml
  - organizer/deployment.yaml
  - organizer/service.yaml
  - personalization/deployment.yaml
  - personalization/service.yaml
vars:
  - name: HTS_NAMESPACE
    objref:
      kind: Service
      name: account
      apiVersion: v1
    fieldref:
      fieldpath: metadata.namespace
  - name: HTS_SVC_ACCOUNT
    objref:
      kind: Service
      name: account
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: HTS_SVC_FACILITY
    objref:
      kind: Service
      name: facility
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: HTS_SVC_ORGANIZER
    objref:
      kind: Service
      name: organizer
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: HTS_SVC_PARTICIPANT
    objref:
      kind: Service
      name: participant
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: HTS_SVC_PERSONALIZATION
    objref:
      kind: Service
      name: personalization
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
