apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hts
resources:
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml
  - account/deployment.yaml
  - account/service.yaml
  - facility/deployment.yaml
  - facility/service.yaml
vars:
  - name: HTS_NAMESPACE
    objref:
      kind: Service
      name: account
      apiVersion: v1
    fieldref:
      fieldpath: metadata.namespace
  - name: HTS_SVC_ACCOUNT
    objref:
      kind: Service
      name: account
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
