apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
resources:
- ../../base
images:
- digest: sha256:48ab5355820896ec8e3d44d6abd611bd5a9741e3168a85626c7721c53e9973b3
  name: facility
  newName: ghcr.io/hu-tao-supremacy/facility-dev
- digest: sha256:b537db0f77b380ad67a2b78b530160745789fe8fa26256001722d85d262c7775
  name: participant
  newName: ghcr.io/hu-tao-supremacy/participant-dev
