apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
resources:
- ../../base
images:
- digest: sha256:48ab5355820896ec8e3d44d6abd611bd5a9741e3168a85626c7721c53e9973b3
  name: facility
  newName: ghcr.io/hu-tao-supremacy/facility-dev
- digest: sha256:8b5f82d2462e776ba2e7d14fddd3e9c329c5676d51e0ed5b1e77da14b4da01e2
  name: participant
  newName: ghcr.io/hu-tao-supremacy/participant-dev
