apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
commonLabels:
  env: staging
resources:
- ../../base
patches:
- path: env.yaml
  target:
    kind: Deployment
images:
- digest: sha256:4ed7d196b3d084427ce46e8d1a8a9da2e78065f95866486fe5357d2f2db0aa9d
  name: facility
  newName: ghcr.io/hu-tao-supremacy/facility-dev
- digest: sha256:b0e8543c8a2ba573504992ce52670acd8351c6c9fc000966343707ba02ec2aaa
  name: organizer
  newName: ghcr.io/hu-tao-supremacy/organizer-dev
- digest: sha256:bd20279490099b1244f6e4588b6e8e7c3f4c4c71cddc990ea5e2c855ca4cd4c5
  name: participant
  newName: ghcr.io/hu-tao-supremacy/participant-dev
