apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
commonLabels:
  env: staging
resources:
- ../../base
patches:
- path: env.yaml
  target:
    kind: Deployment
images:
- digest: sha256:4ed7d196b3d084427ce46e8d1a8a9da2e78065f95866486fe5357d2f2db0aa9d
  name: facility
  newName: ghcr.io/hu-tao-supremacy/facility-dev
- digest: sha256:cb0467cfcfd12cdc149dcba6f5279529d395606370ac93f20e1a41e3d60cbcc1
  name: organizer
  newName: ghcr.io/hu-tao-supremacy/organizer-dev
- digest: sha256:65f15a87f1ca442203c433e576b1476e2f70e956e68f84d0d2c8bdb199c56dd4
  name: participant
  newName: ghcr.io/hu-tao-supremacy/participant-dev
