apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
resources:
- ../../base
images:
- digest: sha256:8802a18eb8239fa44591909301ec03e4b477b243b3d698356f381a1f5e754f1d
  name: facility
  newName: ghcr.io/hu-tao-supremacy/facility-dev
- digest: sha256:b537db0f77b380ad67a2b78b530160745789fe8fa26256001722d85d262c7775
  name: participant
  newName: ghcr.io/hu-tao-supremacy/participant-dev
