apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
commonLabels:
  env: staging
resources:
- ../../base
patches:
- path: env.yaml
  target:
    kind: Deployment
images:
- digest: sha256:b34abc8e540e80ca3dc6decbfd4a6a79e617cdb5612324e05cb46a96edaba7aa
  name: api-gateway
  newName: ghcr.io/hu-tao-supremacy/api-gateway-dev
- digest: sha256:8d0684bba8de0f6e078e68f7b803384c4f832d39f3bcaf3d4860ac62a7a2a683
  name: facility
  newName: ghcr.io/hu-tao-supremacy/facility-dev
- digest: sha256:b0e8543c8a2ba573504992ce52670acd8351c6c9fc000966343707ba02ec2aaa
  name: organizer
  newName: ghcr.io/hu-tao-supremacy/organizer-dev
- digest: sha256:1d40df9c8277cd2bdc21267c8f7237b3ddd8f1b06d139ed778bd39ff8d673bb9
  name: participant
  newName: ghcr.io/hu-tao-supremacy/participant-dev
