apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
resources:
- ../../base
images:
- digest: sha256:2bfc6de822d084f1b409efec92c5cb8dc0890476ec9bc58d525c5ce6ec113460
  name: facility
  newName: ghcr.io/hu-tao-supremacy/facility-dev
