apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
resources:
- ../../base
images:
- digest: sha256:8802a18eb8239fa44591909301ec03e4b477b243b3d698356f381a1f5e754f1d
  name: facility
  newName: ghcr.io/hu-tao-supremacy/facility-dev
