apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hts-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/hu-tao-supremacy/deploys.git
    path: hts/envs/prod
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
